---
- hosts: all
  become: true
  remote_user: vagrant
  tasks:
    - name: collect all managed nodes using jijna template
      template: 
        src: hosts.j2
        dest: /etc/myhosts
      when: inventory_hostname in groups['dev']
