---
- hosts: all
  become: true
  remote_user: vagrant
  tasks: 
    - name: Install php and mariaDB in dev hosts
      yum:
        name: 
          - php
          - mariadb
        state: present

    - name: Install RPM Development Tools in dev hosts
      yum: 
       name: '@RPM Development Tools'
       state: present
      when: inventory_hostname in groups['dev']

    - name: update all packages to latest in dev  hosts
      yum: 
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']

        
        
   


